---
- name: Deploy Flask App from S3
  hosts: flask
  become: yes
  vars:
    app_dir: /home/ec2-user/Flask-Sqlite-Application-group14

  tasks:
    - name: Ensure dependencies are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - unzip
        state: present

    - name: Ensure boto3 and botocore are installed
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3

    - name: Download artifact from S3
      amazon.aws.aws_s3:
        bucket: '{{ s3_bucket }}'
        object: 'artifacts/{{ app_name }}.tar.gz'
        dest: '/tmp/{{ app_name }}.tar.gz'
        mode: get
        region: '{{ region }}'

    - name: Extract artifact
      ansible.builtin.unarchive:
        src: '/tmp/{{ app_name }}.tar.gz'
        dest: '{{ app_dir }}'
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Install requirements
      pip:
        requirements: '{{ app_dir }}/requirements.txt'
        virtualenv: '{{ app_dir }}/venv'
        virtualenv_command: python3 -m venv

    - name: Create systemd service for Flask app
      ansible.builtin.copy:
        dest: /etc/systemd/system/flask-app.service
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory={{ app_dir }}
          Environment="PATH={{ app_dir }}/venv/bin"
          ExecStart={{ app_dir }}/venv/bin/flask run --host=0.0.0.0 --port=5000
          Restart=always
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier=flask-app

          [Install]
          WantedBy=multi-user.target
      notify:
        - reload systemd

    - name: Ensure Flask app is running
      ansible.builtin.systemd:
        name: flask-app
        state: started
        enabled: true

  handlers:
    - name: reload systemd
      ansible.builtin.command: systemctl daemon-reload
