---
- name: Deploy Flask App from S3
  hosts: flask
  become: yes
  vars:
    app_dir: /home/ec2-user/flask-app

  tasks:
    - name: Ensure dependencies are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - unzip
        state: present

    - name: Download artifact from S3
      amazon.aws.aws_s3:
        bucket: '{{ s3_bucket }}'
        object: 'artifacts/{{ app_name }}.tar.gz'
        dest: '/tmp/{{ app_name }}.tar.gz'
        mode: get
        region: '{{ region }}'

    - name: Extract artifact
      ansible.builtin.unarchive:
        src: '/tmp/{{ app_name }}.tar.gz'
        dest: '{{ app_dir }}'
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Install requirements
      pip:
        requirements: '{{ app_dir }}/requirements.txt'
        virtualenv: '{{ app_dir }}/venv'
        virtualenv_command: python3 -m venv

    - name: Restart Flask app (dev mode)
      ansible.builtin.shell: |
        pkill -f "flask run" || true
        source {{ app_dir }}/venv/bin/activate
        nohup flask run --host=0.0.0.0 --port=5000 &
      args:
        chdir: '{{ app_dir }}'
