---
- name: Setup Flask Application
  hosts: flask
  become: yes

  vars:
    app_dir: /home/ec2-user/Flask-Sqlite-Application-group14

  tasks:
    - name: Ensure system packages are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Create application directory
      ansible.builtin.file:
        path: '{{ app_dir }}'
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv venv
        chdir: '{{ app_dir }}'
      args:
        creates: '{{ app_dir }}/venv'

    - name: Install Flask dependencies
      ansible.builtin.pip:
        requirements: '{{ app_dir }}/requirements.txt'
        virtualenv: '{{ app_dir }}/venv'
