---
- name: Update application from Git
  hosts: flask
  become: yes

  vars:
    app_dir: /home/ec2-user/Flask-Sqlite-Application-group14
    repo_url: git@github.com:Elvis-Ikay/Flask-Sqlite-Application-group14.git
    branch: develop

  tasks:
    - name: Ensure application directory exists
      ansible.builtin.file:
        path: '{{ app_dir }}'
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Pull latest changes from Git
      ansible.builtin.git:
        repo: '{{ repo_url }}'
        dest: '{{ app_dir }}'
        version: '{{ branch }}'
        update: yes
        force: yes
        accept_hostkey: yes
