---
- name: Install and start Jenkins on Amazon Linux 2023
  hosts: jenkins
  become: yes

  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Install Java 11 (required by Jenkins)
      ansible.builtin.dnf:
        name: java-11-openjdk-devel
        state: present

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Add Jenkins repository
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        enabled: yes

    - name: Install Jenkins
      ansible.builtin.dnf:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Open firewall port 8080 (if firewalld is running)
      ansible.builtin.firewalld:
        service: http
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes

    - name: Display initial admin password
      ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - debug:
        msg: 'Initial Jenkins admin password: {{ jenkins_initial_password.stdout }}'
